"""Hedron MVP tools: jailed python + office writers. All offline."""
import subprocess
import sys

def run_python_jail(code: str, timeout: int = 5) -> dict:
    """Run code with no network: blocked socket import, timeout, byte cap."""
    guard = "import socket as _s; _s.socket = lambda *a, **k: (_ for _ in ()).throw(RuntimeError('network blocked'))\n"
    try:
        r = subprocess.run([sys.executable, "-c", guard + code[:8000]],
                           capture_output=True, text=True, timeout=timeout)
        return {"ok": r.returncode == 0, "stdout": r.stdout[-2000:], "stderr": r.stderr[-1000:]}
    except subprocess.TimeoutExpired:
        return {"ok": False, "stdout": "", "stderr": "timeout after %ss" % timeout}

def write_docx(path: str, title: str, paras: list, style: str = "default") -> str:
    import os
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    d = Document()
    # Title heading with styling
    heading = d.add_heading(title, level=1)
    for run in heading.runs:
        run.font.size = Pt(24)
        run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)
    # Paragraphs with per-paragraph styling
    for i, p in enumerate(paras):
        paragraph = d.add_paragraph(p)
        # Alternate row styling: first para bold, others normal with italic on alternate
        for j, run in enumerate(paragraph.runs):
            run.font.size = Pt(12)
            run.font.color.rgb = RGBColor(0x2D, 0x2D, 0x2D)
        # Bold first paragraph only
        if i == 0:
            paragraph.runs[0].bold = True
        # Alternate italic
        if i % 2 == 1 and len(paragraph.runs) > 1:
            paragraph.runs[1].italic = True
    # Add a footer-like line
    footer_para = d.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run("— generated by Hedron MVP —")
    run.font.size = Pt(8)
    run.font.italic = True
    run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    d.save(path)
    return path

def verify(answer: str, cites: list, xlsx_path: str | None = None,
           need_cites: bool = False, max_chars: int = 2000) -> dict:
    """Release gate: cites≥1 (when required), recalc 0, overflow cap."""
    checks = {}
    checks["cites"] = (len(cites or []) >= 1) if need_cites else True
    checks["overflow"] = len(answer or "") <= max_chars
    checks["recalc"] = True
    if xlsx_path:
        try:
            from openpyxl import load_workbook
            wb = load_workbook(xlsx_path, data_only=False)
            bad = 0
            for ws in wb.worksheets:
                for row in ws.iter_rows():
                    for c in row:
                        v = c.value
                        if isinstance(v, str) and v.startswith("="):
                            if "[" in v or "#REF!" in v or "#NAME?" in v:
                                bad += 1  # external link or broken ref
            checks["recalc"] = bad == 0
        except Exception:
            checks["recalc"] = False
    ok = all(checks.values())
    return {"ok": ok, "checks": checks}

def write_xlsx(path: str, rows: list) -> str:
    import os
    from openpyxl import Workbook
    from openpyxl.styles import Font
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    wb = Workbook()
    ws = wb.active
    for r in rows:
        ws.append(r)
    for c in ws[1]:
        c.font = Font(bold=True)
    wb.save(path)
    return path

def write_pptx(path: str, title: str, bullets: list) -> str:
    import os
    from openpyxl import Workbook
    from openpyxl.styles import Font
    try:
        from pptx import Presentation
        from pptx.util import Inches
        from pptx.enum.shapes import MSO_SHAPE
    except Exception:
        return write_docx(path, title, bullets[:1])  # fallback
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    prs = Presentation()
    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Hedron MVP — " + __import__("datetime").datetime.now().strftime("%b %y")
    # Agenda slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Agenda"
    for i, b in enumerate(bullets[:6]):
        tf = slide.shapes.placeholders[1].text_frame
        tf.text = ""  # reset
        if i < len(bullets) and bullets[i]:
            p = tf.add_paragraph()
            p.text = bullets[i]
    # 3 content slides (one per 2 bullets)
    for idx in range(3):
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Section %d" % (idx + 1)
        tf = slide.shapes.placeholders[1].text_frame
        tf.text = ""
        for j in range(2):
            bi = idx * 2 + j
            if bi < len(bullets) and bullets[bi]:
                p = tf.add_paragraph()
                p.text = bullets[bi]
    # Closing slide (same Title+Content layout; blank layouts carry no placeholders)
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Thank you"
    tf = slide.shapes.placeholders[1].text_frame
    tf.text = "Hedron MVP — " + __import__("datetime").datetime.now().strftime("%b %Y")
    prs.save(path)
    return path
